server:
  port: 8080
  # 开启压缩功能 好像没体现
  compression:
    enabled: true
    min-response-size: 0
    mime-types: ["text/html","text/xml","application/xml","application/json","application/octet-stream"]
  undertow:
    threads:
      worker: 15
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印日志
  global-config:
    banner: false
dev:
  mysql: 172.16.2.171:3308
  redis: 172.16.2.171
spring:
  application:
    name: dxp-provider-sso
  datasource:
    url: jdbc:mysql://${dev.mysql}/uat-e-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: ${dev.redis}
#    host: 192.168.0.106
#    password: 123456
#    cluster:
#      nodes: 192.168.0.106:7001,192.168.0.106:7002,192.168.0.106:7003,192.168.0.106:7004,192.168.0.106:7005,192.168.0.106:7006
#      max-redirects: 3
#      # 连接超时时间
#      timeout: 10s
#      lettuce:
#        pool:
#          # 连接池中的最小空闲连接
#          min-idle: 1
#          # 连接池中的最大空闲连接
#          max-idle: 16
#          # 连接池的最大数据库连接数
#          max-active: 32
#          # #连接池最大阻塞等待时间（使用负值表示没有限制）
#          max-wait: -1ms
#  cloud:
#    # nacos
#    nacos:
#      discovery:
#        server-addr: 172.16.11.5:28848
#        namespace: DXP-INCUBATOR

  flyway:
    enabled:  false # 开启 Flyway 功能
    cleanDisabled: true # 禁用 Flyway 所有的 drop 相关的逻辑，避免出现跑路的情况。
    locations: # 迁移脚本目录
      - classpath:db/migration # 配置 SQL-based 的 SQL 脚本在该目录下
     # - classpath:cn.iocoder.springboot.lab20.databaseversioncontrol.migration # 配置 Java-based 的 Java 文件在该目录下
    check-location: false # 是否校验迁移脚本目录下。如果配置为 true ，代表需要校验。此时，如果目录下没有迁移脚本，会抛出 IllegalStateException 异常
    url: jdbc:mysql://${dev.mysql}/dxp-master?useSSL=false&useUnicode=true&characterEncoding=UTF-8 # 数据库地址
    user: root # 数据库账号
    password: 123456 # 数据库密码
    # table: dxp_schema_history
logging:
  level:
    com.dqcer: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  log:
    server:
      url: http://localhost:8080