server:
  port: 9091
  undertow:
    threads:
      worker: 15

spring:
  application:
    name: dxp-provider-sso
  datasource:
    url: jdbc:mysql://172.16.2.171:3308/dxp-master?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 172.16.2.171
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: 172.16.11.5:28848
        namespace: DXP-INCUBATOR

# 日志级别
logging:
  level:
    com.dqcer: info

management:
  endpoints:
    web:
      exposure:
        include: "*"