server:
  port: 8080
  # 开启压缩功能 好像没体现
  compression:
    enabled: true
    min-response-size: 0
    mime-types: ["text/html","text/xml","application/xml","application/json","application/octet-stream"]
  undertow:
    threads:
      worker: 15
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印日志
  global-config:
    banner: false
dev:
  mysql: 172.16.11.11:3308
  redis: 172.16.11.11
spring:
  application:
    name: dxp-provider-sso
  redis:
    port: 6379
    host: 127.0.0.1
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.11.5:28848
        namespace: DXP-INCUBATOR
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:9000
  jmx:
    enabled: true # spring-boot-admin 监控 jmx

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.dqcer: debug
feign:
  log:
    server:
      url: http://localhost:8080