spring:
  datasource:
    url: jdbc:mysql://172.16.2.171:3308/a03
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db
    enabled: false

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dqcer
  # 开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true