spring:
  datasource:
    url: jdbc:mysql://172.16.11.11:3308/A04
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    # ∞Ê±æ«®“∆Œª÷√
    locations: classpath:db